import { Platform } from 'react-native';

export const Colors = {
  light: {
    background: "#ffffff",
    foreground: "#0a0910",
    card: "#ffffff",
    cardForeground: "#0a0910",
    popover: "#ffffff",
    popoverForeground: "#0a0910",
    primary: "#e11d48",
    primaryForeground: "#f7f3ef",
    secondary: "#b3b3b3ff",
    secondaryForeground: "#1b1718",
    muted: "#b3b3b3ff",
    mutedForeground: "#b3b3b3ff",
    accent: "#b3b3b3ff",
    accentForeground: "#1b1718",
    destructive: "#d32a2aff",
    constructive: "#1a9447",
    border: "#b3b3b3ff",
    input: "#b3b3b3ff",
    ring: "#e11d48",
    chart1: "#d4803f",
    chart2: "#3f87a9",
    chart3: "#444c80",
    chart4: "#e6d144",
    chart5: "#d4a63f",
    chartBackgroundPrimary: "#ffffff",
    chartBackgroundSecondary: "#ffffff0e",
    sidebar: "#fcfcfc",
    sidebarForeground: "#0a0910",
    sidebarPrimary: "#e11d48",
    sidebarPrimaryForeground: "#f7f3ef",
    sidebarAccent: "#f7f7f9",
    sidebarAccentForeground: "#1b1718",
    sidebarBorder: "#ebeaef",
    sidebarRing: "#e11d48",
    text: "#000000",
  },
  dark: {
    background: "#0b0809",
    foreground: "#fcfcfc",
    card: "#ffffff0e",
    cardForeground: "#fcfcfc",
    popover: "#ffffff0e",
    popoverForeground: "#fcfcfc",
    primary: "#e11d48",
    primaryForeground: "#f7f3ef",
    secondary: "#ffffff1a",
    secondaryForeground: "#fcfcfc",
    muted: "#ffffff0e",
    mutedForeground: "#a1a0af",
    accent: "#ffffff0e",
    accentForeground: "#fcfcfc",
    destructive: "#d32a2aff",
    constructive: "#1a9447", 
    border: "#1b1718",
    input: "#ffffff0e", 
    ring: "#e11d48",
    chart1: "#5961c2",
    chart2: "#4ebc91",
    chart3: "#d4a63f",
    chart4: "#a74ae0",
    chart5: "#e11d48",
    chartBackgroundPrimary: "#ffffff",
    chartBackgroundSecondary: "#ffffff0e",
    sidebar: "#0e0c0dff",
    sidebarForeground: "#fcfcfc",
    sidebarPrimary: "#e11d48",
    sidebarPrimaryForeground: "#f7f3ef",
    sidebarAccent: "#10e0c0dffb1718",
    sidebarAccentForeground: "#fcfcfc",
    sidebarBorder: "#ffffff0e", 
    sidebarRing: "#e11d48",
    text: "#000000",
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "Lato, sans-serif",
  },
  default: {
    sans: "Lato, sans-serif",
  },
});